// Environment definitions: what the user configured (or adb discovered), as persisted.
import type { AdbDevice } from '../env/adb/devices.ts'
import type { EnvironmentKind } from '../env/types.ts'

/** Kinds a definition may have (`host` is internal to transfers). */
export type DefinitionKind = Exclude<EnvironmentKind, 'host'>

export const KINDS: readonly DefinitionKind[] = ['local', 'server', 'ssh', 'adb', 'winuser', 'reverse']
export const SECRET_FIELDS = ['token', 'password', 'passphrase'] as const
export const SECRET_MARKER = '••••••'
export const LOCAL_ID = 'local'

/** Connection settings of a definition; which fields apply depends on the kind. */
export interface EnvironmentConfig {
  /** server, ssh */
  host?: string
  port?: number
  /** server: `tcp://host:port`, `ws://host:port/path` or `wss://...` (instead of host/port) */
  url?: string
  /** server, reverse: shared secret keying the secure channel (reverse: generated by the plugin) */
  token?: string
  /** ssh */
  username?: string
  password?: string
  privateKeyPath?: string
  passphrase?: string
  serverPath?: string
  install?: 'off' | 'auto'
  /** ssh: `auto` (port forwarding, else stdio over exec) or `stdio` */
  transport?: 'auto' | 'stdio'
  readyTimeoutMs?: number
  /** local, ssh, winuser, reverse (passed to the generated connect command) */
  cwd?: string
  /** adb */
  serial?: string
  adb?: string
  /** winuser */
  account?: string
  /** winuser: `shared` (the human's desktop), `private` (its own desktop) or `session` */
  desktop?: 'shared' | 'private' | 'session'
}

/**
 * How a lease occupies an environment.
 *
 * - `headless`: files, commands, processes, tunnels and the tools that do not drive the screen
 *   (e.g. `install_apk`, `app`, `logcat`).
 * - `gui`: additionally the screen: `screenshot`, `input`, `ui`, `windows`, `device`. At most one
 *   lease of an environment is a GUI lease at a time.
 */
export type LeaseMode = 'headless' | 'gui'

export const LEASE_MODES: readonly LeaseMode[] = ['headless', 'gui']

export function isLeaseMode(v: unknown): v is LeaseMode {
  return v === 'headless' || v === 'gui'
}

export interface EnvironmentDefinition {
  id: string
  name: string
  kind: DefinitionKind
  description?: string
  tags?: string[]
  borrowable?: boolean
  /**
   * Headless leases of different sessions may run at the same time (absent: true). `false` makes
   * the environment exclusive: one lease of either mode at a time, the others queue.
   */
  headlessParallel?: boolean
  /** Mode in which mounting occupies the environment (absent: the plugin's `mountMode`, default headless). */
  mountMode?: LeaseMode
  /** The built-in local environment. */
  builtin?: boolean
  /** Found by adb discovery and not persisted yet. */
  discovered?: boolean
  config: EnvironmentConfig
}

/** Definition as shown to the UI: secrets masked, alias and lease settings resolved. */
export interface PublicDefinition extends EnvironmentDefinition {
  alias: string
  headlessParallel: boolean
  /** The mount mode in effect (the definition's own, else the plugin default). */
  effectiveMountMode: LeaseMode
}

/** Input accepted by `upsert` (from the UI; loosely typed on purpose). */
export interface DefinitionInput {
  id?: string
  name?: string
  kind: string
  description?: string
  tags?: unknown
  borrowable?: boolean
  /** `undefined`: keep the saved value; `null`: back to the default (parallel). */
  headlessParallel?: boolean | null
  /** `undefined`: keep the saved value; `null`/`''`: back to the plugin default. */
  mountMode?: string | null
  config?: Record<string, unknown>
}

export interface DiscoveryState {
  adb: AdbDevice[]
  adbError: string | undefined
  at: number
}

export function slug(s: unknown): string {
  return (
    String(s)
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '_')
      .replace(/^_+|_+$/g, '')
      .slice(0, 24) || 'env'
  )
}

/** Tool-name-safe alias for an environment. */
export function aliasFor(id: string): string {
  let a = slug(id)
  if (!/^[a-z]/.test(a)) a = `env_${a}`
  return a
}

/**
 * `id: name [kind, description]` — the stable label of a definition, shared by the `env_list`
 * output and the session's system-prompt list so the two cannot drift apart.
 */
export function definitionLabel(def: EnvironmentDefinition): string {
  return `${def.id}: ${def.name} [${def.kind}${def.description ? `, ${def.description}` : ''}]`
}

/** Whether headless leases of different sessions may coexist (see `LeaseMode`). */
export function isHeadlessParallel(def: EnvironmentDefinition): boolean {
  return def.headlessParallel !== false
}

/**
 * Kinds that were exclusive by default before lease modes existed (`exclusive` defaulted to true).
 * Their exclusivity protected the screen, which GUI leases now protect on their own.
 */
const LEGACY_EXCLUSIVE_KINDS = ['adb', 'winuser']

/**
 * Migrate a persisted definition from the `exclusive` flag to `headlessParallel`. An `exclusive`
 * equal to the old default of its kind carried no choice (the old GUI saved it on every save) and
 * is dropped: adb and Windows-account environments become headless-parallel with an exclusive GUI.
 * An `exclusive: true` the user set on a kind that was shared by default stays exclusive.
 * Returns whether the record changed.
 */
export function migrateDefinition(record: Record<string, unknown>): boolean {
  if (!('exclusive' in record)) return false
  const exclusive = record['exclusive']
  delete record['exclusive']
  if (exclusive === true && !LEGACY_EXCLUSIVE_KINDS.includes(String(record['kind']))) {
    record['headlessParallel'] = false
  }
  return true
}

export function isKind(kind: string): kind is DefinitionKind {
  return (KINDS as readonly string[]).includes(kind)
}
